name: Testing

on:
  push:
    branches:
    - master

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run shfmt on shell scripts.
      run: |
        sudo snap install shfmt
        shopt -s nullglob
        make lint

  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck on shell scripts.
      run: |
        shopt -s nullglob
        make check

  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run linbox in loopback mode.
      run: sudo ./linbox.sh -e 256M -s 512M -L -p "linbox" --verbose --batchmode --flavors "archlinux"
