name: Test

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run test in loopback mode.
      run: sudo ./linbox.sh -e 256M -s 512M -L -p "linbox" --verbose --batchmode
