name: Testing

on:
  push:
    branches:
    - master

jobs:

  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run shellcheck on shell scripts.
      run: |
        shopt -s nullglob
        shellcheck --exclude=SC1090 linbox.sh lib/*/*.sh

  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run linbox in loopback mode.
      run: sudo ./linbox.sh -e 256M -s 512M -L -p "linbox" --verbose --batchmode --phases "wipefs partition encrypt mkfs btrfs"
